controller_list:
  - name: /mhuman/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
    - jright_shoulder_rotz
    - jright_shoulder_roty
    - jright_shoulder_rotx
    - jright_forearm_rotz
    - jright_forearm_roty
    - jright_wrist_rotz
    - jright_wrist_rotx
#    gains:
#      jright_shoulder_rotz:
#        p: 100
#        i: 0.01
#        d: 10
#        i_clamp: 1
#      jright_shoulder_roty:
#        p: 100
#        i: 0.01
#        d: 10
#        i_clamp: 1   
#      jright_shoulder_rotx:
#        p: 100
#        i: 0.01
#        d: 10
#        i_clamp: 1
#      jright_forearm_rotz:
#        p: 100
#        i: 0.01
#        d: 10
#        i_clamp: 1
#      jright_forearm_roty:
#        p: 100
#        i: 0.01
#        d: 10
#        i_clamp: 1
#      jright_wrist_rotz:
#        p: 100
#        i: 0.01
#        d: 10
#        i_clamp: 1   
#      jright_wrist_rotx:
#        p: 100
#        i: 0.01
#        d: 10
#        i_clamp: 1   
  - name: /mhuman/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - jright_grip_rhand
#    gains:
#      jright_grip_rhand:
#        p: 100
#        i: 0.01
#        d: 10
#        i_clamp: 1
         

