controller_list:
  - name: fake_right_arm_controller
    joints:
      - jright_shoulder_rotz
      - jright_shoulder_roty
      - jright_shoulder_rotx
      - jright_forearm_rotz
      - jright_forearm_roty
      - jright_wrist_rotx
      - jright_wrist_rotz
  - name: fake_right_hand_controller
    joints:
      - jright_grip_rhand